name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Запуск каждый день в полночь
  workflow_dispatch:     # Возможность запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: MONZikWasTaken
          outputs: dist/github-contribution-grid-snake.svg
          
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
