name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Запуск каждый день в полночь
  workflow_dispatch:     # Возможность запустить вручную

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout repo content
        uses: actions/checkout@v4

      # Генерация змейки
      - name: Generate Snake files
        uses: Platane/snk@v3
        with:
          github_user_name: MONZikWasTaken
          outputs: dist/snake.svg

      # Загружаем артефакт (необязательно, просто для проверки)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg

      # Публикуем в ветку output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
